version: '2'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    links:
      - 'db:database'
    volumes:
      - /tmp:/mnt/app
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: kingbob
      MYSQL_ROOT_PASSWORD: password
